### ISSUE TITLE
Execution stalls after second encoding request

### ISSUE THREAD

**Issue by alex-ketch** [stencila/executa#141]
To reproduce:
Open GSuita
Create an new "R" node
Run and insert into document
Update code and re-run
Request will never terminate

**Comment by nokome** [comment]
Thanks @alex-ketch that is very useful. Might be useful to add a test e.g. to `src/ws/WebSocketClientServer.test.ts` (or in another file) that sends WS payloads of increasing sizes and see if that is indeed the issue.

**Comment by alex-ketch** [comment]
Sadly still seeing this issue with:
- Server: https://hub.docker.com/layers/stencila/executa-midi/latest/images/sha256-b8ed0bd5049a0e4b1183c8b7e3fdbc3106589cb45ed160c111e7c2b396338dcd?context=explore
- Client: [`v1.11.6`](url)

**Comment by nokome** [comment]
Can not replicate error with `master` (1.11.7) locally (`npm run cli:dev -- serve --ws --http`) and Firefox:

![image](https://user-images.githubusercontent.com/1152336/82976970-995d6600-a034-11ea-93e9-a8a95bdb885f.png)

Will try with latest Docker image now.

**Comment by nokome** [comment]
Can replicate stalling when using latest `stencila/executa-midi`

```sh
nokome@pluto ~/s/s/executa (master) [1]> docker pull stencila/executa-midi
Using default tag: latest
latest: Pulling from stencila/executa-midi
cbdc015de259: Pull complete 
35f8707632bb: Pull complete 
6b786d087f83: Pull complete 
31fb3cd05fdd: Pull complete 
03e41e2e43fb: Pull complete 
f3d9c2390c2f: Pull complete 
c644a6919971: Pull complete 
2cb077204b1d: Pull complete 
0a33cd7f8118: Pull complete 
200b9e2f690e: Pull complete 
94542fd3846f: Pull complete 
422ada9d0ba7: Pull complete 
7b16431d9115: Pull complete 
69a6c76ae0ec: Pull complete 
6c5fa772083c: Pull complete 
174d7d96e989: Pull complete 
c2105085e6d2: Pull complete 
4bb6e19859f9: Pull complete 
65f1c5e8a03e: Pull complete 
859b5e88c230: Pull complete 
15568bba7075: Pull complete 
80adbddd3754: Pull complete 
a18b70ccf25d: Pull complete 
436ac7686ea6: Pull complete 
e88ee0269662: Pull complete 
3ad7006b8fcb: Pull complete 
15a415509f5e: Pull complete 
Digest: sha256:b8ed0bd5049a0e4b1183c8b7e3fdbc3106589cb45ed160c111e7c2b396338dcd
Status: Downloaded newer image for stencila/executa-midi:latest
nokome@pluto ~/s/s/executa (master)> npm run docker:run-image stencila/executa-midi:latest

> @stencila/executa@1.11.7 docker:run-image /home/nokome/stencila/source/executa
> docker run -it --init --rm --cap-add=SYS_ADMIN -p 9000:9000 "stencila/executa-midi:latest"
```

![image](https://user-images.githubusercontent.com/1152336/82977878-46d17900-a037-11ea-882d-8a653530fc7c.png)

I believe that this is because building of the image failed i.e. `latest` does not include the fix to this issue:

**Comment by nokome** [comment]
I've fixed the issue (missing dependency) and the executa images have been rebuilt: https://hub.docker.com/repository/docker/stencila/executa-midi/tags?page=1

I no longer have the issue with stencila/executa-midi 85403b23d54e703e168f55a855c8bfbe0527bad8513cb7de16512222a3333967

**Comment by alex-ketch** [comment]
Can confirm that this bug is ☠️!!
Everything works as intended, closing this issue 🎉
